ALTER TABLE tb_ride_passengers ALTER COLUMN user_id SET DATA TYPE VARCHAR(255);
ALTER TABLE tb_ride_requests ALTER COLUMN passenger_id SET DATA TYPE VARCHAR(255);
ALTER TABLE tb_rides ALTER COLUMN driver_id SET DATA TYPE VARCHAR(255);
ALTER TABLE tb_driver_offers ALTER COLUMN driver_id SET DATA TYPE VARCHAR(255);